ARROW-66/Create_categories_on_the_main_page
raccoongang/edx-theme pull request #1151
Opened 2019-04-16 12:55 UTC by RuslanSkiraRaccoongang

[ARROW-66](https://youtrack.raccoongang.com/issue/ARROW-66)/Create_categories_on_the_main_page

- Cherry-pick from the task [GE-33](https://youtrack.raccoongang.com/issue/GE-33)
- was added classes css and changed index.html to display the category names.

2019-04-16 13:28 UTC, madeira reviewed
предполагаю что эта задача была продемана и проверка на респонсив тоже была

2019-04-16 13:28 UTC, madeira commented on lms/static/sass/base/_override-theme.scss
> +    margin: 0 auto;
тут не хватает свойства box-sizing: border-box;

2019-04-16 13:28 UTC, madeira commented on lms/static/sass/base/_override-theme.scss
> +}
необходима пустая строка в конце файла

2019-04-17 13:31 UTC, madeira requested changes
Необходимо пофиксить конфликты

2019-04-18 11:09 UTC, madeira approved these changes

2019-04-18 13:40 UTC, sendr approved these changes

2019-04-18 13:40 UTC, merged