[HERA-193] markup for the HERA dashboard page
raccoongang/edx-theme pull request #1781
Opened 2020-01-16 09:22 UTC by bydawen

Markup for the dashboard page in the LMS part

https://youtrack.raccoongang.com/issue/HERA-193

2020-01-16 09:39 UTC, ihor-romaniuk commented on lms/static/sass/blocks/_dashboard-hera.scss
> +            -webkit-transform: rotate(360deg);
transform: rotate(360deg);
не хватает основного свойства

2020-01-16 09:40 UTC, ihor-romaniuk commented on lms/static/sass/blocks/_dashboard-hera.scss
> +        }
2 блока с одинаковыми свойствами, объедини их

2020-01-16 09:41 UTC, ihor-romaniuk commented on lms/static/sass/blocks/_dashboard-hera.scss
> +        }
такие же свойства есть и ниже, нужно так же объединить

2020-01-16 09:47 UTC, bydawen commented on lms/static/sass/blocks/_dashboard-hera.scss
> +            -webkit-transform: rotate(360deg);
здесь я псевдоэлементом рисую треугольник, генерил его здесь 
http://apps.eky.hk/css-triangle-generator/
и там они рекомендуют это свойство для , решил поставить на всякий случай
'Add -webkit-transform:rotate(360deg) for a better anti-aliasing in webkit browser '

2020-01-17 16:01 UTC, sendr commented
Need to relocate this page to lms/djangoapps/hera/templates/hera/dashboard-outline-fragment.html.

2020-01-20 09:35 UTC, madeira requested changes
В общем нужно провалидировать на соответствие с БЭМ и поправить это в верстке

2020-01-20 09:35 UTC, madeira commented on lms/static/sass/blocks/_dashboard-hera.scss
> +            &__bg {
тут могут использоваться только модификаторы, в элемент нельзя добавить элемент. Нужно что-то придумать с блоками, потому как структура по БЭМ не верная

2020-01-20 09:35 UTC, madeira commented on lms/templates/dashboard.html
> +            <div class="hera-dashboard__progress__header">
вот такого не должно быть

2020-01-20 09:35 UTC, madeira commented on lms/templates/dashboard.html
> +              <div class="hera-dashboard__progress__header__item">
вот это тоже сократи пожалуйста до элемента, эелмента в элементе элемента не может быть :)

2020-01-20 11:00 UTC, bydawen commented on lms/static/sass/blocks/_dashboard-hera.scss
> +        }
fixed

2020-01-20 11:00 UTC, bydawen commented on lms/static/sass/blocks/_dashboard-hera.scss
> +        }
fixed

2020-01-20 11:00 UTC, bydawen commented on lms/static/sass/blocks/_dashboard-hera.scss
> +            &__bg {
fixed

2020-01-20 11:00 UTC, bydawen commented on lms/templates/dashboard.html
> +            <div class="hera-dashboard__progress__header">
fixed

2020-01-20 11:00 UTC, bydawen commented on lms/templates/dashboard.html
> +              <div class="hera-dashboard__progress__header__item">
fixed

2020-01-20 11:01 UTC, bydawen commented on lms/static/sass/blocks/_dashboard-hera.scss
> +        }
fixed

2020-01-20 11:01 UTC, bydawen commented on lms/static/sass/blocks/_dashboard-hera.scss
> +        }
fixed

2020-01-20 14:10 UTC, madeira approved these changes

2020-01-20 14:10 UTC, merged