sSkillonomy 180/redisign about page
raccoongang/edx-theme pull request #1782
Opened 2020-01-16 09:56 UTC by vlasovmichael

redisign about page

https://youtrack.raccoongang.com/issue/SKILLONOMY-180

2020-01-16 11:20 UTC, bydawen requested changes

2020-01-16 11:20 UTC, bydawen commented on lms/static/sass/common/course-page/_how-to.scss
> +    $c: &;
это что-то лишнее? если переменная, то почему она не объявлена не вначале файла?

2020-01-16 11:20 UTC, bydawen commented on lms/static/sass/common/course-page/_program.scss
> +    $c: &;
тут тот же вопрос

2020-01-16 11:20 UTC, bydawen commented on lms/templates/courseware/course_about.html
> -          </a>
удали заккоменченый код если он не нужен

2020-01-16 11:20 UTC, bydawen commented on lms/templates/courseware/course_about.html
> +        </div> -->
тоже убери, если уже не нужно

2020-01-16 11:20 UTC, bydawen commented on lms/templates/courseware/course_about.html
> +      </div> -->
тоже самое

2020-01-16 11:20 UTC, bydawen commented on lms/static/sass/common/course-page/_about.scss
> +.course-about-list {
ознакомься пожалуйста с наим стайлгайдом, по форматирование отступов между вложеными селекторами
https://raccoongang.atlassian.net/wiki/spaces/MD/pages/1183022/Styleguide

2020-01-16 11:20 UTC, bydawen commented on lms/static/images/arrow-down.svg
> +</svg>
и оптимизируй плз все SVG файлы, что бы они были минифицироваными https://jakearchibald.github.io/svgomg/

2020-01-20 11:13 UTC, bydawen approved these changes

2020-01-23 14:45 UTC, madeira approved these changes

2020-01-23 14:45 UTC, merged