Skillonomy 178/index page
raccoongang/edx-theme pull request #1783
Opened 2020-01-20 16:03 UTC by vlasovmichael

Redesign footer, fixed banner, course block, partners block

https://youtrack.raccoongang.com/issue/SKILLONOMY-178

2020-01-20 16:21 UTC, bydawen commented on lms/static/images/footer-logo.svg
> +</svg>
Пожми плз svg файлы

2020-01-21 13:16 UTC, madeira commented on lms/static/sass/common/_tree-blocks.scss
> +    margin-left: 14px;
В конце файла добавь пустую строку

2020-01-21 13:16 UTC, madeira commented on lms/static/sass/common/login-theme/_login-theme.scss
> +    }
в конце файла добавь пустую строку

2020-01-21 13:16 UTC, madeira commented on lms/static/sass/utils/_const.scss
> +$theme-header-btn-color: #009688;
в конце файла добавь пустую строку

2020-01-23 12:15 UTC, madeira requested changes
1. если у блока нет картинки, нужно задать высоту, что б он выглядел нормально
2. на ховер блока курса не должно быть жёлтой кнопки, сделай зелёную
3. на ховер блока курса была заливка берюзовая, где делась, не понял
4. при фокусе на ссылках в футере, просиходит что-то ужасное, поправь пожалуйста

2020-01-23 16:14 UTC, closed without merging