Skillonomy 179/all courses search fixes
raccoongang/edx-theme pull request #1794
Opened 2020-01-27 17:29 UTC by vlasovmichael

https://youtrack.raccoongang.com/issue/SKILLONOMY-179

2020-01-27 17:35 UTC, madeira requested changes
все файлы .idea/ должны быть убраны из репозитория

2020-01-27 17:55 UTC, madeira requested changes

2020-01-27 17:55 UTC, madeira commented on .gitignore
> +.idea/
последнюю строку добавь

2020-01-27 17:56 UTC, madeira commented on lms/static/sass/base/_override.scss
> +                    font-family: 'Artegra Sans', sans-serif;
Почему тут не используется сокращенная запись `font`

2020-01-28 09:09 UTC, vlasovmichael commented on lms/static/sass/base/_override.scss
> +                    font-family: 'Artegra Sans', sans-serif;
поправил

2020-01-28 10:50 UTC, madeira approved these changes

2020-01-28 10:53 UTC, merged