Rn 14 all elearning btn
raccoongang/edx-theme pull request #218
Opened 2018-07-06 09:38 UTC by Lunyachek

https://youtrack.raccoongang.com/issue/RN-14

2018-07-06 09:49 UTC, otecMuxah requested changes

2018-07-06 09:49 UTC, otecMuxah commented on lms/static/sass/base/_override.scss
> +        //@media screen and (min-width:760px ) {
грохни плз

2018-07-06 09:53 UTC, Lunyachek commented on lms/static/sass/base/_override.scss
> +        //@media screen and (min-width:760px ) {
грохнул

2018-07-06 09:55 UTC, madeira requested changes
замечания с какими ты не сталкивался еще, новые блоки мы создаем по БЭМ, смотри тут
https://raccoongang.atlassian.net/wiki/spaces/MD/pages/1183022/Styleguide

очень высокая вложенность, должна быть маскимум 2 с подходом бэм

и большое множество тэгов без классов, что методология БЭМ не приветствует

2018-07-06 10:42 UTC, Lunyachek commented
Немного апдейтнул, облегчил вложенность, добавил классов

2018-07-06 10:46 UTC, madeira requested changes
И как сделаешь классы как я предлагаю, у тебя вообще не будет вложенности больше 2х

2018-07-06 10:46 UTC, madeira commented on lms/static/sass/base/_override-theme.scss
> +	ol {
вот тут берешь и ставишь класс .short-info-list

2018-07-06 10:46 UTC, madeira commented on lms/static/sass/base/_override-theme.scss
> +		li {
тут short-info-list__item

2018-07-06 10:46 UTC, madeira commented on lms/static/sass/base/_override-theme.scss
> +			img {
short-info-list__img, тут уже селектор в 4 вложенность пошел

2018-07-06 10:46 UTC, madeira commented on lms/static/sass/base/_override-theme.scss
> +			.text {
short-info-list__text

2018-07-06 10:46 UTC, madeira commented on lms/static/sass/base/_override-theme.scss
> +		a {
поставить класс по примеру ниже

2018-07-10 12:43 UTC, madeira requested changes

2018-07-10 12:43 UTC, madeira commented on lms/static/sass/base/_override-theme.scss
> +	.new-container {
переименуй пожалуйста в greeting__container и вынеси из блока

2018-07-10 12:43 UTC, madeira commented on lms/static/sass/base/_override-theme.scss
> +	> li {
добавь класс courses-list__item

2018-07-10 12:43 UTC, madeira commented on lms/static/sass/base/_override-theme.scss
> +		a {
добавить класс на ссылку и вынести в родительский блок

2018-07-10 12:43 UTC, madeira commented on lms/static/sass/base/_override-theme.scss
> +		.short-info-list__img {
вынести в родительский блок

2018-07-10 13:51 UTC, madeira approved these changes

2018-07-11 09:59 UTC, otecMuxah approved these changes

2018-07-11 10:00 UTC, merged