[Desk] hided titles in the instructor page
raccoongang/edx-theme pull request #473
Opened 2018-10-09 14:07 UTC by ihor-romaniuk

Youtrack: https://youtrack.raccoongang.com/issue/DESK-14

2018-10-09 14:09 UTC, madeira approved these changes

2018-10-10 11:31 UTC, idegtiarov requested changes

2018-10-10 11:31 UTC, idegtiarov commented on lms/templates/instructor/instructor_dashboard_2/student_admin.html
> +<%! from django.utils.translation import ugettext as _ %>
settings are not imported and all references will fail.

2018-10-10 11:31 UTC, idegtiarov commented on lms/templates/instructor/instructor_dashboard_2/student_admin.html
> +%if settings.FEATURES.get('ENABLE_INSTRUCTOR_BACKGROUND_TASKS'):
this if statement is redundant upper one and current one could be joined together.

2018-10-10 13:01 UTC, merged