[BI] fixed footer in IE browser
raccoongang/edx-theme pull request #503
Opened 2018-10-18 08:38 UTC by ihor-romaniuk

https://youtrack.raccoongang.com/issue/BI-165

2018-10-18 10:05 UTC, madeira requested changes

2018-10-18 10:05 UTC, madeira commented on lms/static/sass/base/_override.scss
> +}
@ihor-romaniuk ты это в дискашнах и в вики проверь плиз

2018-10-19 07:34 UTC, ihor-romaniuk commented on lms/static/sass/base/_override.scss
> +}
исправил

2018-10-19 07:43 UTC, madeira approved these changes

2018-10-19 07:44 UTC, merged